name: Playwright Test - Approvals Folder

on:
  push:
    paths:
      - 'tests/Ajensia/Approvals/**'  # Trigger when any file in this folder changes
  pull_request:
    paths:
      - 'tests/Ajensia/Approvals/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests in Approvals folder
        run: npx playwright test tests/Ajensia/Approvals/

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

