name: Playwright Tests

on:
  push:
    paths:
      - 'tests/Ajensia/AssetManagement/**'  # Trigger only for AssetManagement changes
  pull_request:
    paths:
      - 'tests/Ajensia/AssetManagement/**'
  workflow_dispatch:  # ✅ Allows manual trigger from GitHub UI

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests in AssetManagement folder (with trace on failure)
        run: npx playwright test tests/Ajensia/AssetManagement/ --trace on

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Check if tests were executed
        run: |
          if [ ! -d playwright-report ]; then
            echo "No tests were executed!"
            exit 1
          fi
